name: Build package

on: 
 push:
 pull_request:
 workflow_dispatch:
 schedule:
    - cron: "0 6,12,18 * * *"
 

jobs:
  build_pkg:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout ya2d
      uses: actions/checkout@v4
      with:
        repository: ps3-pkgi/ya2d
        path: ya2d_ps3

    - name: Checkout mini18n
      uses: actions/checkout@v4
      with:
        repository: ps3-pkgi/mini18n
        path: mini18n

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xz -C ./
        curl -sL https://github.com/ps3dev/PSL1GHT/raw/master/ppu/include/sysutil/sysutil.h -o ps3dev/ppu/include/sysutil/sysutil.h

    - name: Install ya2d
      working-directory: ya2d_ps3/libya2d
      run: |
        make install V=1 VERBOSE=1

    - name: Install mini18n
      working-directory: mini18n
      run: |
        make install V=1 VERBOSE=1

    - name: Get Game Url info
      run: |
        aria2c http://nopaystation.com/tsv/PS3_GAMES.tsv -o pkgfiles/USRDIR/pkgi_games.txt
        aria2c http://nopaystation.com/tsv/PS3_DLCS.tsv -o pkgfiles/USRDIR/pkgi_dlcs.txt
        aria2c http://nopaystation.com/tsv/PS3_THEMES.tsv -o pkgfiles/USRDIR/pkgi_themes.txt
        aria2c http://nopaystation.com/tsv/PS3_AVATARS.tsv -o pkgfiles/USRDIR/pkgi_avatars.txt
        aria2c http://nopaystation.com/tsv/PS3_DEMOS.tsv -o pkgfiles/USRDIR/pkgi_demos.txt
        

    - name: Build PKGi App Package
      run:   make pkg V=1 VERBOSE=1

    - name: Push package artifact
      if: github.event_name != 'push'
      uses: actions/upload-artifact@v4
      with:
        name: pkgi-ps3-build_${{ env.sha_name }}
        path: pkgi.pkg
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
